---
- name: delete existing pm2 processes if running
  command: "pm2 delete all -s"
  args:
    chdir: "{{ project_local_path }}/frontend/"
  ignore_errors: True

- name: Install node components
  command: "npm install"
  become: yes
  args:
    chdir: "{{ project_local_path }}/frontend/"

- name: Build static assets
  command: "npm run build"
  become: yes
  args:
    chdir: "{{ project_local_path }}/frontend/"

- name: start pm2 process
  command: 'pm2 start npm --name "next" -- start'
  args:
    chdir: "{{ project_local_path }}/frontend/"